### PR TITLE
Allow setting worker replica count to 0

### PR DESCRIPTION
**Pull request by accorvin**
Some OpenShift cluster topologies (single node openshift, schedulable master nodes) require creating a cluster with zero worker nodes. We want to be able to deploy clusters with this configuration to more optimally use our cloud resource quotas. This change is necessary to allow OSIA to provision a cluster with zero workers. Prior to this change, if you set the count to zero with the CLI `--worker-replicas` flag, Jinja would interpret zero as False and therefore use the default value of 3. This moves the logic for setting the default value to the base cloud class. I moved the master node replica count logic to the same place for consistency.

### CODE REVIEW

**Comment by accorvin** [comment]
@mijaros let me know what you think of this change when you have a chance.

**Comment by mijaros** [comment]
Looking into it, and it makes sense, for me the base issue is to use the default once it is not set. This does exactly that. Thank you for the contribution.

**Review by mijaros — APPROVED** [review]
The change makes sense and allows new ability to the tool. 👍

**Comment by accorvin** [comment]
Thanks @mijaros! Do you know when you plan to cut a new release that will include this change?

**Pull request merged**
